name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the Docker image
    - name: Build the Docker image
      run: |
        docker build -t flask-app .

    # Step 4: Run container tests (optional)
    - name: Test container
      run: |
        docker run -d -p 5000:5000 flask-app
        sleep 10
        curl -f http://localhost:5000

    # Step 5: Deploy to server (local Docker deployment)
    - name: Deploy to local Docker
      run: |
        docker run -d -p 5000:5000 flask-app
