name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build the Docker image
      run: |
        docker build -t flask-app .

    # Step 5: Test container (optional)
    - name: Test container
      run: |
        docker run -d -p 5000:5000 flask-app
        sleep 10
        curl -f http://localhost:5000

    # Step 6: Tag and push the image to Docker Hub
    - name: Tag and push to Docker Hub
      run: |
        docker tag flask-app meghanamurthyy/flask-app:latest
        docker push meghanamurthyy/flask-app:latest
